### ISSUE TITLE
How can i use gen.sh file for ios ?

### ISSUE THREAD

**Issue by 9bany** [FWGS/microndk#1]

**Comment by mittorn** [comment]
It must be called from makefile
Use these scripts as reference
https://github.com/mittorn/xash3d-ios/blob/master/scripts/build-hlsdk.sh
https://github.com/mittorn/xash3d-ios/blob/master/scripts/build-all-mods.sh
https://github.com/mittorn/xash3d-ios/blob/master/scripts/run-microndk.sh
https://github.com/mittorn/xash3d-ios/blob/master/scripts/run-xcodebuild.sh
It is really better to use some project generator instead of these deprecated thing, waf should support targeting ios

**Comment by 9bany** [comment]
I'm hope we has a example project for it ✌️
